### ISSUE TITLE
Can dependency on App Version be removed?

### ISSUE THREAD

**Issue by azizhk** [bugsnag/webpack-bugsnag-plugins#19] opened 2018-10-22 08:25 UTC
Hey, so we have some caching of javascript assets across versions following this guide.
https://webpack.js.org/guides/caching/

But the sourcemap uploader plugin has a dependency on app version because bugsnag website matches version and url both to extract sourcemap.

And then it fails fetching sourcemap for our error where we have retained a javascript asset across versions.

**Comment by snmaynard** [comment] 2018-10-22 22:27
I recommend getting in touch with support@bugsnag.com for support on this one. However something to note,

You can upload a sourcemap for a URL across different app versions. So for example `/vendor.abcdhashhere.js` can be uploaded for both version 1.1 and 1.2 - even though they havent changed.

I'm going to close this issue as its not a bug with the plugin - but please do get in touch with support.

**Closed by snmaynard** 2018-10-22 22:27 UTC

**Comment by azizhk** [comment] 2018-10-23 09:07
I did contact support. They suggested stripping out version altogether from events and source maps.
Zendesk ID: 12518

I replied saying that I'll try sending a constant version across builds. (Not happily though 😜)
